project: sample-app2
profile: DEBUG
build:
- name: app
  type: app
  sources: all
  rpath: "."
  build:
  - sources: all
    name: libsum10
    type: static_lib
  - sources: all
    name: libmul10
    type: shared_lib

