# Enable C++ support
language: cpp

sudo: required
dist: trusty

# Compiler selection
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - ninja-build
            - gcc-7
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#    - os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty-6.0
#          packages:
#            - cmake
#            - cmake-data
#            - ninja-build
#            - clang-6.0
#      env:
#        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"

# Install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc++-dev libc++abi-dev
  # Verify cmake versions
  - cmake --version

# Only watch the master branch
branches:
  only:
    - master

# Build steps
script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" ..
  - cmake --build .
