project: sample-app
build:
- name: app
  type: app
  sources: all
  build:
  - sources:
    - sum.cpp
    name: libsum
    type: static_lib
  - sources:
    - mul.cpp
    name: libmul
    type: shared_lib

